### ISSUE TITLE
Chef Provisioning- Vagrant

### ISSUE THREAD

**Issue by DarshanMurthy** [chef/chef-provisioning#373] opened 2015-06-24 17:13 UTC
Hi All,

Steps I followed:

Step 1: Cloned the Git code (https://github.com/chef/chef-provisioning.git)
Step 2: gem install chef-provisioning chef-provisioning-vagrant
Step 3: export CHEF_DRIVER=vagrant

Step 4: export VAGRANT_DEFAULT_PROVIDER=virtualbox
Step 5: chef-client -z vagrant_linux.rb simple.rb

Error log files:

```
2015-06-24T10:10:56-07:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /Users/dtumkursreeni/chef
  One version per cookbook

[2015-06-24T10:10:56-07:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.4.0.rc.0
[2015-06-24T10:10:56-07:00] INFO: *** Chef 12.4.0.rc.0 ***
[2015-06-24T10:10:56-07:00] INFO: Chef-client pid: 14889
[2015-06-24T10:10:58-07:00] INFO: Run List is []
[2015-06-24T10:10:58-07:00] INFO: Run List expands to []
[2015-06-24T10:10:58-07:00] INFO: Starting Chef Run for dtumkursreeni
[2015-06-24T10:10:58-07:00] INFO: Running start handlers
[2015-06-24T10:10:58-07:00] INFO: Start handlers complete.
[2015-06-24T10:10:58-07:00] INFO: HTTP Request Returned 404 Not Found: Object not found: 
resolving cookbooks for run list: []
[2015-06-24T10:10:58-07:00] INFO: Loading cookbooks []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2015-06-24T10:10:58-07:00] WARN: Class Chef::Resource::VagrantBox does not declare 'provides :vagrant_box'.
[2015-06-24T10:10:58-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:58-07:00] WARN: Chef::Resource::VagrantBox is marked as providing DSL vagrant_box, but provides :vagrant_box was never called!
[2015-06-24T10:10:58-07:00] WARN: In Chef 13, this will break: you must call provides to mark the names you provide, even if you also override provides? yourself.
[2015-06-24T10:10:58-07:00] WARN: Class Chef::Resource::VagrantBox does not declare 'provides :vagrant_box'.
[2015-06-24T10:10:58-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:58-07:00] WARN: Class Chef::Resource::Machine does not declare 'provides :machine'.
[2015-06-24T10:10:58-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:58-07:00] WARN: Chef::Resource::Machine is marked as providing DSL machine, but provides :machine was never called!
[2015-06-24T10:10:58-07:00] WARN: In Chef 13, this will break: you must call provides to mark the names you provide, even if you also override provides? yourself.
[2015-06-24T10:10:58-07:00] WARN: Class Chef::Resource::Machine does not declare 'provides :machine'.
[2015-06-24T10:10:58-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:58-07:00] WARN: Node dtumkursreeni has an empty run list.
Converging 2 resources
Recipe: @recipe_files::/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/vagrant_linux.rb
  * vagrant_box[precise64] action create[2015-06-24T10:10:58-07:00] INFO: Processing vagrant_box[precise64] action create (@recipe_files::/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/vagrant_linux.rb line 77)
[2015-06-24T10:10:58-07:00] WARN: Class Chef::Provider::VagrantBox does not declare 'provides :vagrant_box'.
[2015-06-24T10:10:58-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
 (up to date)
Recipe: @recipe_files::/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/simple.rb
  * machine[mario] action converge[2015-06-24T10:10:59-07:00] INFO: Processing machine[mario] action converge (@recipe_files::/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/simple.rb line 77)
[2015-06-24T10:10:59-07:00] WARN: Class Chef::Provider::Machine does not declare 'provides :machine'.
[2015-06-24T10:10:59-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:59-07:00] WARN: Class Chef::Resource::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2015-06-24T10:10:59-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:59-07:00] WARN: Chef::Resource::VagrantCluster is marked as providing DSL vagrant_cluster, but provides :vagrant_cluster was never called!
[2015-06-24T10:10:59-07:00] WARN: In Chef 13, this will break: you must call provides to mark the names you provide, even if you also override provides? yourself.
[2015-06-24T10:10:59-07:00] WARN: Class Chef::Resource::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2015-06-24T10:10:59-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:59-07:00] INFO: Processing vagrant_cluster[/Users/dtumkursreeni/.chef/vms] action create (basic_chef_client::block line 77)
[2015-06-24T10:10:59-07:00] WARN: Class Chef::Provider::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2015-06-24T10:10:59-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:10:59-07:00] INFO: Processing directory[/Users/dtumkursreeni/.chef/vms] action create (basic_chef_client::block line 15)
[2015-06-24T10:10:59-07:00] INFO: Processing file[/Users/dtumkursreeni/.chef/vms/Vagrantfile] action create (basic_chef_client::block line 16)
[2015-06-24T10:11:00-07:00] INFO: Processing file[/Users/dtumkursreeni/.chef/vms/mario.vm] action create (basic_chef_client::block line 232)
[2015-06-24T10:11:00-07:00] WARN: Class Chef::Resource::ChefNode does not declare 'provides :chef_node'.
[2015-06-24T10:11:00-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:11:00-07:00] WARN: Chef::Resource::ChefNode is marked as providing DSL chef_node, but provides :chef_node was never called!
[2015-06-24T10:11:00-07:00] WARN: In Chef 13, this will break: you must call provides to mark the names you provide, even if you also override provides? yourself.
[2015-06-24T10:11:00-07:00] WARN: Class Chef::Resource::ChefNode does not declare 'provides :chef_node'.
[2015-06-24T10:11:00-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-24T10:11:00-07:00] INFO: Processing chef_node[mario] action create (basic_chef_client::block line 77)
[2015-06-24T10:11:00-07:00] WARN: Class Chef::Provider::ChefNode does not declare 'provides :chef_node'.
[2015-06-24T10:11:00-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.

    
    ================================================================================
    Error executing action `converge` on resource 'machine[mario]'
    ================================================================================
    
    RuntimeError
    ------------
    vagrant up mario failed!
    STDOUT:Bringing machine 'mario' up with 'vmware_fusion' provider...
    ==> mario: Box 'precise64' could not be found. Attempting to find and install...
        mario: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
        mario: Box Version: >= 0
    ==> mario: Adding box 'precise64' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
        mario: Downloading: precise64

    STDERR:An error occurred while downloading the remote file. The error
    message, if any, is reproduced below. Please fix this error and try
    again.
    
    Couldn't open file /Users/dtumkursreeni/.chefvm/configurations/int/vms/precise64
    
    Resource Declaration:
    ---------------------
    # In /Users/dtumkursreeni/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/dsl/recipe.rb
    
     77:           return send(method_symbol, *args, &block)
     78:         end
    
    Compiled Resource:
    ------------------
    # Declared in /Users/dtumkursreeni/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/dsl/recipe.rb:77:in `method_missing'
    
    machine("mario") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"dtumkursreeni", :signing_key_filename=>"/Users/dtumkursreeni/.chef/dtumkursreeni.pem"}}
      driver "vagrant"
      machine_options {:vagrant_options=>{"vm.box"=>"precise64"}}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/simple.rb"
      attribute_modifiers [["tags", #<Proc:0x007fb70a8f62b8@/Users/dtumkursreeni/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish.rb:149>]]
      converge true
    end
    
[2015-06-24T10:11:02-07:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-06-24T10:11:02-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-24T10:11:02-07:00] ERROR: Exception handlers complete
[2015-06-24T10:11:02-07:00] FATAL: Stacktrace dumped to /Users/dtumkursreeni/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 6.375067 seconds
[2015-06-24T10:11:02-07:00] ERROR: machine[mario] (@recipe_files::/Users/dtumkursreeni/Just_Example/chef-provisioning/docs/examples/simple.rb line 77) had an error: RuntimeError: vagrant up mario failed!
STDOUT:Bringing machine 'mario' up with 'vmware_fusion' provider...
==> mario: Box 'precise64' could not be found. Attempting to find and install...
    mario: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    mario: Box Version: >= 0
==> mario: Adding box 'precise64' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
    mario: Downloading: precise64

STDERR:An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/dtumkursreeni/.chefvm/configurations/int/vms/precise64

[2015-06-24T10:11:02-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
dtumkursreeni-mac:examples dtumkursreeni
```

**Comment by tyler-ball** [comment] 2015-07-01 01:39
Hey @DarshanMurthy it looks like this is a duplicate of https://github.com/chef/chef-provisioning/issues/367 which we closed, so I'm going to close this

**Closed by tyler-ball** 2015-07-01 01:39 UTC
