### ISSUE TITLE
Chef::Exceptions::ContentLengthMismatch Response body length XXXX does not match HTTP Content-Length header XXXX

### ISSUE THREAD

**Issue by chriscameron** [chef/chef-provisioning#446] opened 2015-09-17 01:07 UTC
I'm getting this content length mismatch error at random intervals regardless of the provider used. It seems to happen when syncing the cookbooks to the target machine using the machine resource. 

Stack trace:

RuntimeError: machine[scraper1] (@recipe_files::/rails/thdr/amazon_ec2.rb line 136) had an error: RuntimeError: Error: command 'chef-client -l auto' exited with code 1.

      RuntimeError: machine[scraper1] (@recipe_files::/rails/thdr/amazon_ec2.rb line 136) had an error: RuntimeError: Error: command 'chef-client -l auto' exited with code 1.

      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/transport/ssh.rb:271:in `error!'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:31:in `block in execute'
      /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
      /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_provider_action_handler.rb:54:in `perform_action'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:29:in `execute'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/install_sh.rb:55:in `block (2 levels) in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/run_context.rb:273:in `open_stream'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_provider_action_handler.rb:59:in `open_stream'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/install_sh.rb:52:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/run_context.rb:273:in `open_stream'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_provider_action_handler.rb:59:in `open_stream'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/install_sh.rb:51:in `converge'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:21:in `converge'
      /Users/wer/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provider/machine.rb:63:in `block in <class:Machine>'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:46:in `block in action'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:269:in `run'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
      /opt/chefdk/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
      /opt/chefdk/bin/chef-client:55:in `load'
      /opt/chefdk/bin/chef-client:55:in `<main>'

**Comment by chrodriguez** [comment] 2015-11-03 19:24
I'm getting the same Exception, so I've made some tests trying to isolate this problem. I've created a repo https://github.com/chrodriguez/chef-provisioning-vagrant-error with sample code to be run with: 

* chefdk 0.9.0
* Tested with Ubuntu 14.04 and MacOS: both cases failed randomly

Run this sandbox with:

```
chef-zero -z vagrant.rb my-cluster.rb
```

Some times it runs OK, if thats the case, then enter to the created machine and remove cached cookbooks:

```
cd vms && vagrant ssh -c "sudo rm -fr /var/chef/cache/cookbooks" && cd ..
```

I'm not 100% sure where to look at, so I begin following code, and ended at net-ssh-2.9.2/lib/net/ssh/service/forward.rb:263 `#prepare_client` method. I've modified the code by collecting bytes per channel and I've concluded that at this point data is transferred completelly, but chef-client still fails. So I think some channel may be closed before all threads are ended...

**Comment by chrodriguez** [comment] 2015-11-04 18:45
May be @tyler-ball or @jkeiser can give us more information about where to look at

**Comment by georeith** [comment] 2015-11-17 19:45
Having the same issue

**Comment by EYurchenko** [comment] 2015-11-20 19:13
One workstation and several clouds I am trying to deploy/converge VMs into.
If latency between the workstation and cloud is low (we have less than 30ms across North America) then no failures at all.
If latency between the workstation and cloud is high enough (>120ms) convergence consistently fails with the error:
================================================================================
                Error Syncing Cookbooks:
                ================================================================================

                Unexpected Error:
                -----------------
                Chef::Exceptions::ContentLengthMismatch: Response body length 2096996 does not match HTTP Content-Length header 3658571.

Experimented with different cookbooks and seems it has something to do with number/size of cookbooks to be synced as for 'small' cookbooks (that don't depend on may other CBs) the problem does not appear.

**Comment by EYurchenko** [comment] 2015-11-23 16:10
The more I look at this the weirder it looks. For clarity I am running my chef-provisioning recipe at 'workstation'. I run it once, it syncs whatever cookbooks can be synced and fails with the error quoted above. Then...
So case one:
I login into remote machine and set up a tunnel(port-forwarding) by means of ordinarry ssh client. Then execute 'chef-client' that syncs missing(not properly downloaded) cookbooks over this tunnel and converges successfully.

Case two:
I run a simple script on my 'workstation' to create a tunnel (basically crafted from what chef-provisioning/transport/ssh.rb has in its code):
```ruby
require 'timeout'
require 'net/ssh'

session = begin
  Net::SSH.start('10.56.87.16', 'local', { timeout:10 })
end
actual_remote_port, actual_remote_host = session.forward.active_remote_destinations[[7799, '127.0.0.1']]
if !actual_remote_port
  session.forward.remote(7799, 'localhost', 7799, 'localhost') do |new_remote_port, new_remote_host|
    actual_remote_host = new_remote_host
    actual_remote_port = new_remote_port || :error
  end
end
# Kick SSH until we get a response
session.loop { !actual_remote_port }
if actual_remote_port == :error
  return nil
end
# loop until ctrl-C is pressed
int_pressed = false
trap("INT") { int_pressed = true }
session.loop(0.1) { not int_pressed }
```

And then run 'chef-client' on target VM - it fails with exactly the same error on exactly the same file! I know that if fails on http://localhost:7799/file_store/checksums/69d7b635c1ff57117b125ad3219dd2cf request so I try to wget the same URL and it succeeds.
At this point I am lost... -(

For failure scenario I ran tcpdump on both workstation and target VM simultaneously tracking all communication on local interface (cannot attach .cap files here). Obviously not all the data sent by chef-zero to chef-client arrives safely at the target VM. So the error IS valid. -(((

**Comment by pburkholder** [comment] 2015-11-23 19:56
I'll work on reproducing this case tomorrow. Thanks for your patience

Can you please confirm which driver(s) you are using with chef-provisioning? 

--Peter

**Comment by georeith** [comment] 2015-11-23 20:09
@pburkholder I am getting the error with the AWS driver and using chef zero

**Comment by EYurchenko** [comment] 2015-11-23 20:33
We use opennebula driver

**Comment by chrodriguez** [comment] 2015-11-24 05:15
We were using vagrant

**Comment by EYurchenko** [comment] 2015-11-24 16:15
Obviously it is a problem of how net/ssh handles the port forwarding.
This is what we have in terms of tcp connections:
```
Workstation <--------|---------------------------|---> Target VM
chef-zero:7799 <---> A <----ssh connection-----> B:7799 <----> chef-client
```
Between process A (ssh-client) on Workstation and process B (ssh-server) on VM we have an SSH connection. On top of that we establish port-forwarding so process B starts listening on port 7799 and forward the packets arriving at this port to chef-zerro:7799 running on Workstation.
Here is what we see when a problem exists and the chef-client syncs cookbooks:
```
chef-zero:7799 ---TCP segment10-> A -----> B --- TCP segment10--> chef-client
chef-zero:7799 <-----ACK10------- A        B <------ ACK10------- chef-client
chef-zero:7799 ---TCP segment11-> A
chef-zero:7799 <-----ACK11------- A
chef-zero:7799 ---TCP segment12-> A -----> B --- TCP segment11--> chef-client
chef-zero:7799 <-----ACK12------- A        B <----- ACK11-------- chef-client
chef-zero:7799 ---TCP segment13-> A 
chef-zero:7799 <-----ACK13------- A
chef-zero:7799 ---TCP segment14-> A -----> B --- TCP segment12--> chef-client
chef-zero:7799 <-----ACK14------- A        B <----- ACK12-------- chef-client
```
Chef-zero talks to process A much faster than process A to B and chef-client (latency!), we are seeing even TCP window overflow (but that's ok, not critical).
And when chef-zero thinks it has finished transmission (it has no idea it is talking to remote site) it hangs up with TCP FIN. And for some reason at this point B sends FIN as well despite it has not transferred all the segments to chef-client yet!
chef-zero:7799 ----------- FIN ---------> A -----> B --------------- FIN -------> chef-client
This is why we are missing some last segments on chef-client.
Now how to remediate this. Looking at why wget works but chef-client run does not I noticed difference in HTTP requests. Chef-client sends:
```
GET /file_store/checksums/69d7b635c1ff57117b125ad3219dd2cf HTTP/1.1
Accept: */*
<snip>
X-Chef-Version: 12.5.1
<snip>
Connection: close
```
Look at Connection: element - it tells the HTTP server to close the connection when it is done so it does.
This element exists by default from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb line 1376:
```ruby
    def request(req, body = nil, &block)  # :yield: +response+
      unless started?
        start {
          req['connection'] ||= 'close'
```
Now let's have our chef-client to synchronize cookbooks sending a little bit different headers. On my target VM:
```ruby
root@test-vm:/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef# git diff
diff --git a/cookbook/synchronizer.rb b/cookbook/synchronizer.rb
index fc8e739..3114cba 100644
--- a/cookbook/synchronizer.rb
+++ b/cookbook/synchronizer.rb
@@ -274,7 +274,7 @@ class Chef
     # downloaded to the path +destination+ which is relative to the Chef file
     # cache root.
     def download_file(url, destination)
-      raw_file = server_api.get_rest(url, true)
+      raw_file = server_api.get_rest(url, true, { 'connection' => 'Keep-Alive' })

       Chef::Log.info("Storing updated #{destination} in the cache.")
       cache.move_to(raw_file.path, destination)
```
After that change we'll have these HTTP headers for cookbooks sync activity:
```
GET /file_store/checksums/69d7b635c1ff57117b125ad3219dd2cf HTTP/1.1
Connection: Keep-Alive
Accept: */*
X-Chef-Version: 12.5.1
```
and chef-zero does not close connections any longer, it patiently waits for TCP FIN to arrive from remote client and the error in the question disappears, everything syncs and converges perfectly well.
I'd love the change in synchronizer.rb to go live but I am not an expert in Chef/Ruby so you guys tell me what's the best way to proceed. Plus somebody definitely should look at how port-forwarding is done by net/ssh.
So turns out it's not a chef-provisioning issue -( sorry...

**Comment by pburkholder** [comment] 2015-11-24 23:52
I'm not able to repro this ContentLengthMismatch issue when running with 250ms latency and 15% packet loss. Can you please confirm the versions of ChefDK that you have on your workstation with `chef --version` and/or the chef-client version you're running on the target VMs?

P.S. https://github.com/tylertreat/comcast is pretty handy.

**Comment by EYurchenko** [comment] 2015-11-24 23:57
```
local@test-vm:~$ chef-client --version
Chef: 12.5.1
```
Does your cookbook have a file at least 3M of size?

**Comment by EYurchenko** [comment] 2015-12-01 05:31
Updated chefdk to 0.10.0 and having the same problem.
```
local@chef-prov-ws:~/workspace/cookbooks/bb_zabbix_agent$ dpkg-query -l | grep chef
ii  chefdk                           0.10.0-1                         amd64        The full stack of chefdk
```
Here is another proof that it is not about chef-provisioning but rather about Net:SSH tunnels.
At workstation there is a file large enough to generate the error. I am giving its md5sum here because it is how it is seen at chef-zero HTTP server (look at GET url later in this post):
```
local@chef-prov-ws:~$ md5sum /home/local/.berkshelf/cookbooks/php-a3a80fb8367f96506a2f9f26ea26be63c82d08fd/files/windows/go-pear.phar
69d7b635c1ff57117b125ad3219dd2cf  /home/local/.berkshelf/cookbooks/php-a3a80fb8367f96506a2f9f26ea26be63c82d08fd/files/windows/go-pear.phar
local@chef-prov-ws:~$ ls -l /home/local/.berkshelf/cookbooks/php-a3a80fb8367f96506a2f9f26ea26be63c82d08fd/files/windows/go-pear.phar
-rw-rw-r-- 1 local local 3658571 Nov 30 19:03 /home/local/.berkshelf/cookbooks/php-a3a80fb8367f96506a2f9f26ea26be63c82d08fd/files/windows/go-pear.phar
```
Ping target VM to see latency
```
local@chef-prov-ws:~$ ping 10.56.87.16
PING 10.56.87.16 (10.56.87.16) 56(84) bytes of data.
64 bytes from 10.56.87.16: icmp_seq=1 ttl=56 time=126 ms
64 bytes from 10.56.87.16: icmp_seq=2 ttl=56 time=125 ms
64 bytes from 10.56.87.16: icmp_seq=3 ttl=56 time=125 ms
64 bytes from 10.56.87.16: icmp_seq=4 ttl=56 time=125 ms
64 bytes from 10.56.87.16: icmp_seq=5 ttl=56 time=125 ms
^C
--- 10.56.87.16 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 125.713/125.952/126.290/0.487 ms
```
Set up a SSH connection to target VM with remote port forwarding:
```
local@chef-prov-ws:~$ cat ~/tunnel.rb
require 'rubygems'
require 'net/ssh'

Net::SSH.start("10.56.87.16", "local") do |ssh|
  ssh.forward.remote(7799, "localhost", 7799)
  ssh.loop { true }
end

local@chef-prov-ws:~$ ruby ~/tunnel.rb
...<process hanging here untill terminated>...
```
Now to target VM and the simplest script to get a file over HTTP over a tunnel:
```
local@test-vm:~$ dpkg-query -l | grep chef
ii  chef                             12.5.1-1                         amd64        The full stack of chef

local@test-vm:~$ cat get_file.rb
require 'chef/client'

Chef::Config[:chef_server_url] = 'http://localhost:7799'
Chef::Config[:node_name] = 'test-vm'
Chef::Config[:client_key] = '/etc/chef/client.pem'
Chef::Config[:ssl_verify_mode] = :verify_none

def server_api
  Chef::REST.new(Chef::Config[:chef_server_url])
end

url = '/file_store/checksums/69d7b635c1ff57117b125ad3219dd2cf'
raw_file = server_api.get_rest(url, true)
local@test-vm:~$ /opt/chef/embedded/bin/ruby get_file.rb
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http/validate_content_length.rb:102:in `validate': Response body length 2096964 does not match HTTP Content-Length header 3658571. (Chef::Exceptions::ContentLengthMismatch)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http/validate_content_length.rb:60:in `handle_stream_complete'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:240:in `block in apply_stream_complete_middleware'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:238:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:238:in `inject'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:238:in `apply_stream_complete_middleware'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:174:in `block in streaming_request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http/basic_client.rb:88:in `block in request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1421:in `block (2 levels) in transport_request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:162:in `reading_body'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1420:in `block in transport_request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1384:in `request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
        from /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http/basic_client.rb:65:in `request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:264:in `block in send_http_request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:298:in `block in retrying_http_errors'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:296:in `loop'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:296:in `retrying_http_errors'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:260:in `send_http_request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/http.rb:170:in `streaming_request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/rest.rb:180:in `streaming_request'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/rest.rb:118:in `get'
        from get_file.rb:13:in `<main>'

```

Now back to workstation and set up ordinary tunnel (no Ruby here, just ssh client)
```
local@chef-prov-ws:~$ ssh -R 7799:localhost:7799 local@10.56.87.16
```

And on target VM
```
local@test-vm:~$ /opt/chef/embedded/bin/ruby get_file.rb
local@test-vm:~$
```
!!! No errors printed !!!

**Comment by pburkholder** [comment] 2015-12-02 21:42
We've been able to replicate this issue and confirm that this PR, https://github.com/net-ssh/net-ssh/issues/280, resolves it.

The current workaround: build `net-ssh`, `chef` and `chef-provisioning` against the https://github.com/causton81/net-ssh/tree/channel_close_after_output branch, as roughly outlined here: https://gist.github.com/pburkholder/05455d33d4a9f83a54b6#file-testfix-md

The fix:
- Await the merge of channel close into either net-ssh 3.x or 2.x
- Update chef-provisioning to use the new net-ssh release

**Comment by tyler-ball** [comment] 2015-12-02 21:58
@pburkholder I think we should be fine to pull in net-ssh 3.x.  That doesn't say we won't discover an issue during testing, but we can at least try.

**Comment by tyler-ball** [comment] 2015-12-17 02:45
relevant issue - https://github.com/test-kitchen/busser/issues/32

**Comment by tyler-ball** [comment] 2015-12-29 18:36
Update on this - was merged to master and is currently sitting in the [3.0.2.rc.1](https://github.com/net-ssh/net-ssh/tree/v3.0.2.rc1) release of net-ssh.

The ChefDK (and a bunch of its dependencies) are pinned to `~> 2.x` of net-ssh right now so I'm going through and determining where we need to update that.  Once I've updated the dependencies to `3.0.2.rc.1` and generated a current channel build, I will post a link here on how to obtain it for testing.

**Closed** 2016-01-15 17:55 UTC

**Comment by tyler-ball** [comment] 2016-01-15 20:41
Okay!  We now have a ChefDK package available which includes net-ssh 3.0.2.  Would you try following the instructions at https://github.com/chef/chef-dk#pre-release-candidates to download the latest `current` channel package and see if it solves your issues?

**Comment by chrodriguez** [comment] 2016-01-22 02:40
Everything is working fine! I've try it with Vagrant and Vsphere and now it works great!

**Comment by EYurchenko** [comment] 2016-02-19 14:00
Works as expected with Opennebula. Thanks!
Impatiently waiting when this makes into a stable release.

**Comment by Paul424** [comment] 2016-03-09 22:37
Just a heads-up for others that encounter this issue; updating the ChefDK to latest or current (channel) has no use if your actually using chef from a ruby version managed by rvm..... I actually had success after running bundle update which upgraded: chef-zero 4.2.3 (was 4.0) and net-ssh 2.9.4 (was 2.9.2) and chef 12.1.2 (was 12.1.1). Thanks all for the detailed investigation on this subject!
