### ISSUE TITLE
chef_version convergence option is ignored for windows machines

### ISSUE THREAD

**Issue by joelwilson** [chef/chef-provisioning#300] opened 2015-03-03 18:01 UTC
Unlike the Linux [install.sh](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb) convergence strategy, the Windows [install.msi](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_msi.rb) strategy does not take into account the `chef_version` in `convergence_options`, so Windows nodes always have the latest Chef client installed. Of course, this can be problematic when the latest version introduces bugs as is sometimes the case.

**Comment by thommay** [comment] 2015-07-13 11:19
Same as #327

**Comment by tyler-ball** [comment] 2015-07-28 20:22
Closing this as a duplicate of #327 since we are tracking it there - thanks for the original report @joelwilson!

**Closed by tyler-ball** 2015-07-28 20:22 UTC
Labels: Developing
